/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public enum InterfaceActionStateValue implements org.apache.thrift.TEnum {
  /**
   * The interface action state is active
   */
  Active(0),
  /**
   * The interface action state is inactive
   */
  Inactive(1),
  /**
   * The interface action state is 'A'
   */
  State_A(2),
  /**
   * The interface action state is 'B'
   */
  State_B(3),
  /**
   * The interface action state is 'C'
   */
  State_C(4),
  /**
   * The interface action state is 'D'
   */
  State_D(5),
  /**
   * The interface action state is 'E'
   */
  State_E(6),
  /**
   * The interface action state is 'F'
   */
  State_F(7),
  /**
   * The interface action state is 'G'
   */
  State_G(8),
  /**
   * The interface action state is 'H'
   */
  State_H(9),
  /**
   * The interface action state is 'I'
   */
  State_I(10),
  /**
   * The interface action state is 'J'
   */
  State_J(11),
  /**
   * The interface action state is 'K'
   */
  State_K(12),
  /**
   * The interface action state is 'L'
   */
  State_L(13),
  /**
   * The interface action state is 'M'
   */
  State_M(14),
  /**
   * The interface action state is 'N'
   */
  State_N(15),
  /**
   * The interface action state is 'O'
   */
  State_O(16),
  /**
   * The interface action state is 'P'
   */
  State_P(17),
  /**
   * The interface action state is 'Q'
   */
  State_Q(18),
  /**
   * The interface action state is 'R'
   */
  State_R(19),
  /**
   * The interface action state is 'S'
   */
  State_S(20),
  /**
   * The interface action state is 'T'
   */
  State_T(21),
  /**
   * The interface action state is 'U'
   */
  State_U(22),
  /**
   * The interface action state is 'V'
   */
  State_V(23),
  /**
   * The interface action state is 'W'
   */
  State_W(24),
  /**
   * The interface action state is 'X'
   */
  State_X(25),
  /**
   * The interface action state is 'Y'
   */
  State_Y(26),
  /**
   * The interface action state is 'Z'
   */
  State_Z(27);

  private final int value;

  private InterfaceActionStateValue(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static InterfaceActionStateValue findByValue(int value) { 
    switch (value) {
      case 0:
        return Active;
      case 1:
        return Inactive;
      case 2:
        return State_A;
      case 3:
        return State_B;
      case 4:
        return State_C;
      case 5:
        return State_D;
      case 6:
        return State_E;
      case 7:
        return State_F;
      case 8:
        return State_G;
      case 9:
        return State_H;
      case 10:
        return State_I;
      case 11:
        return State_J;
      case 12:
        return State_K;
      case 13:
        return State_L;
      case 14:
        return State_M;
      case 15:
        return State_N;
      case 16:
        return State_O;
      case 17:
        return State_P;
      case 18:
        return State_Q;
      case 19:
        return State_R;
      case 20:
        return State_S;
      case 21:
        return State_T;
      case 22:
        return State_U;
      case 23:
        return State_V;
      case 24:
        return State_W;
      case 25:
        return State_X;
      case 26:
        return State_Y;
      case 27:
        return State_Z;
      default:
        return null;
    }
  }
}
