/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public enum InterfaceActionKeyState implements org.apache.thrift.TEnum {
  /**
   * A push type key is pressed
   */
  Pressed(0),
  /**
   * A push type key is released
   */
  Released(1),
  /**
   * A switch type key is pressed
   */
  Clicked(2);

  private final int value;

  private InterfaceActionKeyState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static InterfaceActionKeyState findByValue(int value) { 
    switch (value) {
      case 0:
        return Pressed;
      case 1:
        return Released;
      case 2:
        return Clicked;
      default:
        return null;
    }
  }
}
