/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public enum RingTransferSequenceState implements org.apache.thrift.TEnum {
  /**
   * The ring transfer sequence state is active
   */
  Active(0),
  /**
   * The ring transfer sequence state is inactive
   */
  Inactive(1),
  /**
   * The ring transfer sequence state is partially (some of the ring transfers are in the required state, but not all of them)
   */
  PartiallyActive(2);

  private final int value;

  private RingTransferSequenceState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RingTransferSequenceState findByValue(int value) { 
    switch (value) {
      case 0:
        return Active;
      case 1:
        return Inactive;
      case 2:
        return PartiallyActive;
      default:
        return null;
    }
  }
}
