/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;

/**
 * Contains information required to identify a ring transfer or a ring transfer sequence
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public class RingTransferId implements org.apache.thrift.TBase<RingTransferId, RingTransferId._Fields>, java.io.Serializable, Cloneable, Comparable<RingTransferId> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RingTransferId");

  private static final org.apache.thrift.protocol.TField API_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("apiName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CONTROLLED_PROFILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("controlledProfileName", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RingTransferIdStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RingTransferIdTupleSchemeFactory();

  /**
   * The API name of the ring transfer
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String apiName; // required
  /**
   * The name of the controlled profile
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String controlledProfileName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * The API name of the ring transfer
     */
    API_NAME((short)1, "apiName"),
    /**
     * The name of the controlled profile
     */
    CONTROLLED_PROFILE_NAME((short)2, "controlledProfileName");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // API_NAME
          return API_NAME;
        case 2: // CONTROLLED_PROFILE_NAME
          return CONTROLLED_PROFILE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.API_NAME, new org.apache.thrift.meta_data.FieldMetaData("apiName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CONTROLLED_PROFILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("controlledProfileName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RingTransferId.class, metaDataMap);
  }

  public RingTransferId() {
  }

  public RingTransferId(
    java.lang.String apiName,
    java.lang.String controlledProfileName)
  {
    this();
    this.apiName = apiName;
    this.controlledProfileName = controlledProfileName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RingTransferId(RingTransferId other) {
    if (other.isSetApiName()) {
      this.apiName = other.apiName;
    }
    if (other.isSetControlledProfileName()) {
      this.controlledProfileName = other.controlledProfileName;
    }
  }

  @Override
  public RingTransferId deepCopy() {
    return new RingTransferId(this);
  }

  @Override
  public void clear() {
    this.apiName = null;
    this.controlledProfileName = null;
  }

  /**
   * The API name of the ring transfer
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getApiName() {
    return this.apiName;
  }

  /**
   * The API name of the ring transfer
   */
  public RingTransferId setApiName(@org.apache.thrift.annotation.Nullable java.lang.String apiName) {
    this.apiName = apiName;
    return this;
  }

  public void unsetApiName() {
    this.apiName = null;
  }

  /** Returns true if field apiName is set (has been assigned a value) and false otherwise */
  public boolean isSetApiName() {
    return this.apiName != null;
  }

  public void setApiNameIsSet(boolean value) {
    if (!value) {
      this.apiName = null;
    }
  }

  /**
   * The name of the controlled profile
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getControlledProfileName() {
    return this.controlledProfileName;
  }

  /**
   * The name of the controlled profile
   */
  public RingTransferId setControlledProfileName(@org.apache.thrift.annotation.Nullable java.lang.String controlledProfileName) {
    this.controlledProfileName = controlledProfileName;
    return this;
  }

  public void unsetControlledProfileName() {
    this.controlledProfileName = null;
  }

  /** Returns true if field controlledProfileName is set (has been assigned a value) and false otherwise */
  public boolean isSetControlledProfileName() {
    return this.controlledProfileName != null;
  }

  public void setControlledProfileNameIsSet(boolean value) {
    if (!value) {
      this.controlledProfileName = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case API_NAME:
      if (value == null) {
        unsetApiName();
      } else {
        setApiName((java.lang.String)value);
      }
      break;

    case CONTROLLED_PROFILE_NAME:
      if (value == null) {
        unsetControlledProfileName();
      } else {
        setControlledProfileName((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case API_NAME:
      return getApiName();

    case CONTROLLED_PROFILE_NAME:
      return getControlledProfileName();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case API_NAME:
      return isSetApiName();
    case CONTROLLED_PROFILE_NAME:
      return isSetControlledProfileName();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RingTransferId)
      return this.equals((RingTransferId)that);
    return false;
  }

  public boolean equals(RingTransferId that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_apiName = true && this.isSetApiName();
    boolean that_present_apiName = true && that.isSetApiName();
    if (this_present_apiName || that_present_apiName) {
      if (!(this_present_apiName && that_present_apiName))
        return false;
      if (!this.apiName.equals(that.apiName))
        return false;
    }

    boolean this_present_controlledProfileName = true && this.isSetControlledProfileName();
    boolean that_present_controlledProfileName = true && that.isSetControlledProfileName();
    if (this_present_controlledProfileName || that_present_controlledProfileName) {
      if (!(this_present_controlledProfileName && that_present_controlledProfileName))
        return false;
      if (!this.controlledProfileName.equals(that.controlledProfileName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetApiName()) ? 131071 : 524287);
    if (isSetApiName())
      hashCode = hashCode * 8191 + apiName.hashCode();

    hashCode = hashCode * 8191 + ((isSetControlledProfileName()) ? 131071 : 524287);
    if (isSetControlledProfileName())
      hashCode = hashCode * 8191 + controlledProfileName.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RingTransferId other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetApiName(), other.isSetApiName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApiName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.apiName, other.apiName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetControlledProfileName(), other.isSetControlledProfileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetControlledProfileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.controlledProfileName, other.controlledProfileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RingTransferId(");
    boolean first = true;

    sb.append("apiName:");
    if (this.apiName == null) {
      sb.append("null");
    } else {
      sb.append(this.apiName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("controlledProfileName:");
    if (this.controlledProfileName == null) {
      sb.append("null");
    } else {
      sb.append(this.controlledProfileName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (apiName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'apiName' was not present! Struct: " + toString());
    }
    if (controlledProfileName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'controlledProfileName' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RingTransferIdStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RingTransferIdStandardScheme getScheme() {
      return new RingTransferIdStandardScheme();
    }
  }

  private static class RingTransferIdStandardScheme extends org.apache.thrift.scheme.StandardScheme<RingTransferId> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RingTransferId struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // API_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.apiName = iprot.readString();
              struct.setApiNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CONTROLLED_PROFILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.controlledProfileName = iprot.readString();
              struct.setControlledProfileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RingTransferId struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.apiName != null) {
        oprot.writeFieldBegin(API_NAME_FIELD_DESC);
        oprot.writeString(struct.apiName);
        oprot.writeFieldEnd();
      }
      if (struct.controlledProfileName != null) {
        oprot.writeFieldBegin(CONTROLLED_PROFILE_NAME_FIELD_DESC);
        oprot.writeString(struct.controlledProfileName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RingTransferIdTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RingTransferIdTupleScheme getScheme() {
      return new RingTransferIdTupleScheme();
    }
  }

  private static class RingTransferIdTupleScheme extends org.apache.thrift.scheme.TupleScheme<RingTransferId> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RingTransferId struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.apiName);
      oprot.writeString(struct.controlledProfileName);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RingTransferId struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.apiName = iprot.readString();
      struct.setApiNameIsSet(true);
      struct.controlledProfileName = iprot.readString();
      struct.setControlledProfileNameIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

