/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;

/**
 * Exception type used to indicate that an error has occured.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public class TurretApiException extends org.apache.thrift.TException implements org.apache.thrift.TBase<TurretApiException, TurretApiException._Fields>, java.io.Serializable, Cloneable, Comparable<TurretApiException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TurretApiException");

  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("ErrorCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ERROR_AS_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("ErrorAsString", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TurretApiExceptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TurretApiExceptionTupleSchemeFactory();

  /**
   * Unique number indicating the error
   */
  public int ErrorCode; // required
  /**
   * Short description of the problem, useful for logging
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String ErrorAsString; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * Unique number indicating the error
     */
    ERROR_CODE((short)1, "ErrorCode"),
    /**
     * Short description of the problem, useful for logging
     */
    ERROR_AS_STRING((short)2, "ErrorAsString");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERROR_CODE
          return ERROR_CODE;
        case 2: // ERROR_AS_STRING
          return ERROR_AS_STRING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ERRORCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("ErrorCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "TurretErrorCode")));
    tmpMap.put(_Fields.ERROR_AS_STRING, new org.apache.thrift.meta_data.FieldMetaData("ErrorAsString", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TurretApiException.class, metaDataMap);
  }

  public TurretApiException() {
  }

  public TurretApiException(
    int ErrorCode,
    java.lang.String ErrorAsString)
  {
    this();
    this.ErrorCode = ErrorCode;
    setErrorCodeIsSet(true);
    this.ErrorAsString = ErrorAsString;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TurretApiException(TurretApiException other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ErrorCode = other.ErrorCode;
    if (other.isSetErrorAsString()) {
      this.ErrorAsString = other.ErrorAsString;
    }
  }

  @Override
  public TurretApiException deepCopy() {
    return new TurretApiException(this);
  }

  @Override
  public void clear() {
    setErrorCodeIsSet(false);
    this.ErrorCode = 0;
    this.ErrorAsString = null;
  }

  /**
   * Unique number indicating the error
   */
  public int getErrorCode() {
    return this.ErrorCode;
  }

  /**
   * Unique number indicating the error
   */
  public TurretApiException setErrorCode(int ErrorCode) {
    this.ErrorCode = ErrorCode;
    setErrorCodeIsSet(true);
    return this;
  }

  public void unsetErrorCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  /** Returns true if field ErrorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  public void setErrorCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERRORCODE_ISSET_ID, value);
  }

  /**
   * Short description of the problem, useful for logging
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getErrorAsString() {
    return this.ErrorAsString;
  }

  /**
   * Short description of the problem, useful for logging
   */
  public TurretApiException setErrorAsString(@org.apache.thrift.annotation.Nullable java.lang.String ErrorAsString) {
    this.ErrorAsString = ErrorAsString;
    return this;
  }

  public void unsetErrorAsString() {
    this.ErrorAsString = null;
  }

  /** Returns true if field ErrorAsString is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorAsString() {
    return this.ErrorAsString != null;
  }

  public void setErrorAsStringIsSet(boolean value) {
    if (!value) {
      this.ErrorAsString = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ERROR_CODE:
      if (value == null) {
        unsetErrorCode();
      } else {
        setErrorCode((java.lang.Integer)value);
      }
      break;

    case ERROR_AS_STRING:
      if (value == null) {
        unsetErrorAsString();
      } else {
        setErrorAsString((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ERROR_CODE:
      return getErrorCode();

    case ERROR_AS_STRING:
      return getErrorAsString();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ERROR_CODE:
      return isSetErrorCode();
    case ERROR_AS_STRING:
      return isSetErrorAsString();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TurretApiException)
      return this.equals((TurretApiException)that);
    return false;
  }

  public boolean equals(TurretApiException that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ErrorCode = true;
    boolean that_present_ErrorCode = true;
    if (this_present_ErrorCode || that_present_ErrorCode) {
      if (!(this_present_ErrorCode && that_present_ErrorCode))
        return false;
      if (this.ErrorCode != that.ErrorCode)
        return false;
    }

    boolean this_present_ErrorAsString = true && this.isSetErrorAsString();
    boolean that_present_ErrorAsString = true && that.isSetErrorAsString();
    if (this_present_ErrorAsString || that_present_ErrorAsString) {
      if (!(this_present_ErrorAsString && that_present_ErrorAsString))
        return false;
      if (!this.ErrorAsString.equals(that.ErrorAsString))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ErrorCode;

    hashCode = hashCode * 8191 + ((isSetErrorAsString()) ? 131071 : 524287);
    if (isSetErrorAsString())
      hashCode = hashCode * 8191 + ErrorAsString.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TurretApiException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetErrorCode(), other.isSetErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ErrorCode, other.ErrorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetErrorAsString(), other.isSetErrorAsString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorAsString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ErrorAsString, other.ErrorAsString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TurretApiException(");
    boolean first = true;

    sb.append("ErrorCode:");
    sb.append(this.ErrorCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ErrorAsString:");
    if (this.ErrorAsString == null) {
      sb.append("null");
    } else {
      sb.append(this.ErrorAsString);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'ErrorCode' because it's a primitive and you chose the non-beans generator.
    if (ErrorAsString == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ErrorAsString' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TurretApiExceptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TurretApiExceptionStandardScheme getScheme() {
      return new TurretApiExceptionStandardScheme();
    }
  }

  private static class TurretApiExceptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<TurretApiException> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TurretApiException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ErrorCode = iprot.readI32();
              struct.setErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ERROR_AS_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ErrorAsString = iprot.readString();
              struct.setErrorAsStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetErrorCode()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'ErrorCode' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TurretApiException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(struct.ErrorCode);
      oprot.writeFieldEnd();
      if (struct.ErrorAsString != null) {
        oprot.writeFieldBegin(ERROR_AS_STRING_FIELD_DESC);
        oprot.writeString(struct.ErrorAsString);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TurretApiExceptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TurretApiExceptionTupleScheme getScheme() {
      return new TurretApiExceptionTupleScheme();
    }
  }

  private static class TurretApiExceptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<TurretApiException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TurretApiException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.ErrorCode);
      oprot.writeString(struct.ErrorAsString);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TurretApiException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.ErrorCode = iprot.readI32();
      struct.setErrorCodeIsSet(true);
      struct.ErrorAsString = iprot.readString();
      struct.setErrorAsStringIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

