#
# Autogenerated by Thrift Compiler (0.19.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
Ok = 0
InvalidArgument = 1
InvalidSpeechUnit = 2
WrongLoginState = 3
CannotSendRequest = 4
LineUnavailable = 5
LineBusy = 6
SpeechUnitBusy = 7
InvalidLine = 8
NoIncomingCall = 9
LineIsNotRinging = 10
SpeechUnitHasNoCall = 11
NoFreeLineAvailable = 12
FunctionUnavailable = 13
NoConsultation = 14
LineIsNotInHold = 15
LoginSuccessful = 400
NoConnectionToSm = 401
AuthenticationFailed = 402
DatabaseError = 403
UnknownProfile = 404
LdapError = 405
LicenseNotAvailable = 406
LoadTLSCertError = 407
InvalidRingTransfer = 600
RingTransferIsOnlyForSignalization = 601
RingTransferIsAlreadyInThatState = 602
RingTransferIsMissingOnServer = 603
RingTransferHasNoLocalInstance = 604
RingTransferControlledProfileLoggedOut = 605
RingTransferKagConflict = 606
RingTransferStateChangeTimeout = 607
InvalidRingTransferSequence = 620
RingTransferSequenceIsOnlyForSignalization = 621
RingTransferSequenceIsAlreadyInThatState = 622
RingTransferSequenceIsNotInverting = 623
RingTransferSequenceIsMissingOnServer = 624
RingTransferSequenceStateChangeTimeout = 625
InvalidInterfaceAction = 640
InterfaceActionIsOnlyForSignalization = 641
InterfaceActionIsAlreadyInThatState = 642
InvalidInterfaceActionState = 643
Unknown = 9999
