/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public enum DeviceType implements org.apache.thrift.TEnum {
  Handset(0),
  Headset(1),
  MicrophoneWithoutSpeaker(2),
  MicrophoneWithSpeaker(3);

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DeviceType findByValue(int value) { 
    switch (value) {
      case 0:
        return Handset;
      case 1:
        return Headset;
      case 2:
        return MicrophoneWithoutSpeaker;
      case 3:
        return MicrophoneWithSpeaker;
      default:
        return null;
    }
  }
}
