/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.unify.osx.turret.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2023-09-29")
public enum TurretState implements org.apache.thrift.TEnum {
  /**
   * The turret is logged out
   */
  Logout(0),
  /**
   * The turret is in Receive Calls Only mode
   */
  ReceiveCallsOnly(1),
  /**
   * The turret is logged in with a profile
   */
  Login(2),
  Unknown(255);

  private final int value;

  private TurretState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TurretState findByValue(int value) { 
    switch (value) {
      case 0:
        return Logout;
      case 1:
        return ReceiveCallsOnly;
      case 2:
        return Login;
      case 255:
        return Unknown;
      default:
        return null;
    }
  }
}
